In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
file_train = pd.read_csv('train.csv')

df_train = pd.DataFrame(file_train)
df_train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
file_test = pd.read_csv('test.csv')

df_test = pd.DataFrame(file_test)

In [5]:
labels = df_train.iloc[:, 0]
pixels = df_train.iloc[:, 1:]

In [6]:
from sklearn import svm

svc = svm.SVC(
    kernel='poly',
    C=1,
    degree=2,
)

svc.fit(pixels, labels)

predicted = svc.predict(df_test)

In [14]:
ans = pd.DataFrame({'ImageId': range(1,len(predicted) + 1), 'Label': predicted})
ans.head()

   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3

In [15]:
ans.to_csv('ans.csv', index=False)